# Generated by Django 5.2.8 on 2026-02-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MorphologieICD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("libelle_ar", models.CharField(blank=True, max_length=200)),
                (
                    "comportement",
                    models.CharField(
                        choices=[
                            ("0", "Bénin"),
                            ("1", "Incertain"),
                            ("2", "In situ"),
                            ("3", "Malin primitif"),
                            ("6", "Malin métastatique"),
                        ],
                        default="3",
                        max_length=1,
                    ),
                ),
                ("groupe", models.CharField(blank=True, max_length=100)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Morphologie ICD-O-3",
                "db_table": "morphologie_icd",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TopographieICD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("libelle_ar", models.CharField(blank=True, max_length=200)),
                ("categorie", models.CharField(blank=True, max_length=100)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Topographie ICD-O-3",
                "db_table": "topographie_icd",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_diagnostic", models.DateField()),
                ("date_premier_symptome", models.DateField(blank=True, null=True)),
                (
                    "base_diagnostic",
                    models.CharField(
                        choices=[
                            ("0", "Clinique seul"),
                            ("1", "Clinique + examens paracliniques"),
                            ("2", "Chirurgie / autopsie sans histologie"),
                            ("4", "Marqueurs biochimiques / immunologiques"),
                            ("5", "Cytologie"),
                            ("6", "Histologie de métastase"),
                            ("7", "Histologie de tumeur primitive"),
                            ("9", "Inconnu"),
                        ],
                        default="9",
                        max_length=1,
                    ),
                ),
                ("topographie_code", models.CharField(blank=True, max_length=10)),
                ("topographie_libelle", models.CharField(blank=True, max_length=200)),
                (
                    "lateralite",
                    models.CharField(
                        choices=[
                            ("0", "Non applicable"),
                            ("1", "Droit"),
                            ("2", "Gauche"),
                            ("3", "Bilatéral"),
                            ("9", "Inconnu"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("morphologie_code", models.CharField(blank=True, max_length=10)),
                ("morphologie_libelle", models.CharField(blank=True, max_length=200)),
                (
                    "grade_histologique",
                    models.CharField(
                        choices=[
                            ("I", "Grade I – bien différencié"),
                            ("II", "Grade II – moyennement différencié"),
                            ("III", "Grade III – peu différencié"),
                            ("IV", "Grade IV – indifférencié"),
                            ("U", "Inconnu / non applicable"),
                        ],
                        default="U",
                        max_length=3,
                    ),
                ),
                (
                    "tnm_t",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TX", "TX – Non évaluable"),
                            ("T0", "T0 – Pas de tumeur"),
                            ("Tis", "Tis – In situ"),
                            ("T1", "T1"),
                            ("T1a", "T1a"),
                            ("T1b", "T1b"),
                            ("T1c", "T1c"),
                            ("T2", "T2"),
                            ("T2a", "T2a"),
                            ("T2b", "T2b"),
                            ("T3", "T3"),
                            ("T3a", "T3a"),
                            ("T4", "T4"),
                            ("T4a", "T4a"),
                            ("T4b", "T4b"),
                            ("T4c", "T4c"),
                            ("T4d", "T4d"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "tnm_n",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NX", "NX – Non évaluable"),
                            ("N0", "N0 – Pas de métastase"),
                            ("N1", "N1"),
                            ("N1a", "N1a"),
                            ("N1b", "N1b"),
                            ("N1c", "N1c"),
                            ("N2", "N2"),
                            ("N2a", "N2a"),
                            ("N2b", "N2b"),
                            ("N2c", "N2c"),
                            ("N3", "N3"),
                            ("N3a", "N3a"),
                            ("N3b", "N3b"),
                            ("N3c", "N3c"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "tnm_m",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MX", "MX – Non évaluable"),
                            ("M0", "M0 – Pas de métastase"),
                            ("M1", "M1 – Métastase à distance"),
                            ("M1a", "M1a"),
                            ("M1b", "M1b"),
                            ("M1c", "M1c"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "tnm_edition",
                    models.CharField(blank=True, default="8", max_length=5),
                ),
                (
                    "tnm_type",
                    models.CharField(
                        choices=[
                            ("c", "cTNM – Clinique"),
                            ("p", "pTNM – Pathologique"),
                            ("y", "yTNM – Post-thérapeutique"),
                        ],
                        default="c",
                        max_length=1,
                    ),
                ),
                (
                    "stade_ajcc",
                    models.CharField(
                        choices=[
                            ("0", "Stade 0 – In situ"),
                            ("I", "Stade I"),
                            ("IA", "Stade IA"),
                            ("IB", "Stade IB"),
                            ("II", "Stade II"),
                            ("IIA", "Stade IIA"),
                            ("IIB", "Stade IIB"),
                            ("IIC", "Stade IIC"),
                            ("III", "Stade III"),
                            ("IIIA", "Stade IIIA"),
                            ("IIIB", "Stade IIIB"),
                            ("IIIC", "Stade IIIC"),
                            ("IV", "Stade IV"),
                            ("U", "Inconnu"),
                        ],
                        default="U",
                        max_length=5,
                    ),
                ),
                (
                    "recepteur_re",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positif", "Positif"),
                            ("negatif", "Négatif"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recepteur_rp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positif", "Positif"),
                            ("negatif", "Négatif"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "her2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positif", "Positif (3+)"),
                            ("equivoque", "Équivoque (2+)"),
                            ("negatif", "Négatif (0/1+)"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ki67",
                    models.CharField(blank=True, help_text="% Ki67", max_length=20),
                ),
                (
                    "psa",
                    models.CharField(blank=True, help_text="PSA ng/mL", max_length=20),
                ),
                ("autres_marqueurs", models.TextField(blank=True)),
                (
                    "taille_tumeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "nombre_ganglions",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "metastases_sites",
                    models.CharField(
                        blank=True, help_text="Sites métastatiques", max_length=300
                    ),
                ),
                (
                    "etablissement_diagnostic",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "medecin_diagnostiqueur",
                    models.CharField(blank=True, max_length=150),
                ),
                ("numero_bloc_anapath", models.CharField(blank=True, max_length=50)),
                ("cim10_code", models.CharField(blank=True, max_length=10)),
                ("cim10_libelle", models.CharField(blank=True, max_length=200)),
                (
                    "est_principal",
                    models.BooleanField(default=True, help_text="Diagnostic principal"),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostics_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="patients.patient",
                    ),
                ),
                (
                    "morphologie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostics",
                        to="diagnostics.morphologieicd",
                    ),
                ),
                (
                    "topographie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostics",
                        to="diagnostics.topographieicd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostic",
                "verbose_name_plural": "Diagnostics",
                "db_table": "diagnostics",
                "ordering": ["-date_diagnostic"],
            },
        ),
    ]
