from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Nouveaux champs sur Diagnostic
        migrations.AddField('Diagnostic', 'numero_dossier',          models.CharField(blank=True, max_length=50)),
        migrations.AddField('Diagnostic', 'medecin_referent',        models.CharField(blank=True, max_length=150)),
        migrations.AddField('Diagnostic', 'statut_dossier',          models.CharField(choices=[('en_cours','En cours'),('valide','Validé'),('archive','Archivé')], default='en_cours', max_length=20)),
        migrations.AddField('Diagnostic', 'type_diagnostic',         models.CharField(choices=[('initial','Diagnostic initial'),('recidive','Récidive'),('nouveau_primitif','Nouveau primitif'),('metastase','Métastase')], default='initial', max_length=20)),
        migrations.AddField('Diagnostic', 'categorie_cancer',        models.CharField(choices=[('solide','Tumeur solide'),('liquide','Tumeur liquide (hématologique)')], default='solide', max_length=10)),
        migrations.AddField('Diagnostic', 'differentiation',         models.TextField(blank=True)),
        migrations.AddField('Diagnostic', 'variante_histologique',   models.CharField(blank=True, max_length=100)),
        migrations.AddField('Diagnostic', 'etat_cancer',             models.CharField(choices=[('localise','Localisé'),('extension_regionale','Extension régionale'),('metastatique','Métastatique'),('non_determine','Non déterminé')], default='non_determine', max_length=25)),
        migrations.AddField('Diagnostic', 'performance_status',      models.CharField(blank=True, max_length=1, choices=[('0','PS 0'),('1','PS 1'),('2','PS 2'),('3','PS 3'),('4','PS 4'),('U','Inconnu')])),
        migrations.AddField('Diagnostic', 'pronostic_evaluation',    models.CharField(blank=True, max_length=20, choices=[('favorable','Favorable'),('intermediaire','Intermédiaire'),('defavorable','Défavorable'),('inconnu','Inconnu')])),
        migrations.AddField('Diagnostic', 'tnm_descripteurs',        models.CharField(blank=True, max_length=100)),
        migrations.AddField('Diagnostic', 'tnm_certitude',           models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'tnm_date_evaluation',     models.DateField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'tnm_commentaire',         models.TextField(blank=True)),
        migrations.AddField('Diagnostic', 'methodes_confirmation_text',  models.CharField(blank=True, max_length=300)),
        migrations.AddField('Diagnostic', 'conf_histologie_tumeur',      models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'conf_cytologie',              models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'conf_microscopie_sans_histo', models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'conf_marqueurs_biologiques',  models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'conf_imagerie',               models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'conf_biopsie_medullaire',     models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'recepteur_re_pourcentage',    models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'recepteur_rp_pourcentage',    models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'her2_fish',   models.CharField(blank=True, max_length=15, choices=[('amplifie','Amplifié'),('non_amplifie','Non amplifié'),('non_fait','Non fait')])),
        migrations.AddField('Diagnostic', 'cea',         models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'ca_19_9',     models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'ca_125',      models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'afp',         models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'pdl1',        models.CharField(blank=True, max_length=20)),
        migrations.AddField('Diagnostic', 'mmr_status',  models.CharField(blank=True, max_length=15, choices=[('deficient','Déficient (dMMR)'),('proficient','Proficient (pMMR)'),('inconnu','Inconnu')])),
        migrations.AddField('Diagnostic', 'taille_tumeur_axe_max',     models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
        migrations.AddField('Diagnostic', 'taille_tumeur_3d',          models.CharField(blank=True, max_length=50)),
        migrations.AddField('Diagnostic', 'nombre_ganglions_preleves', models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'nombre_metastases',         models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'volume_tumoral',            models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
        migrations.AddField('Diagnostic', 'invasion_vasculaire',       models.BooleanField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'invasion_perineurale',      models.BooleanField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'img_scanner',               models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'img_irm_cerebrale',         models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'img_pet_scan',              models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'img_echographie',           models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'img_radiographie',          models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'img_scintigraphie',         models.BooleanField(default=False)),
        migrations.AddField('Diagnostic', 'medecin_anatomopathologiste', models.CharField(blank=True, max_length=150)),
        migrations.AddField('Diagnostic', 'laboratoire_anapath',         models.CharField(blank=True, max_length=200)),
        migrations.AddField('Diagnostic', 'date_analyse_anapath',        models.DateField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'technique_prelevement',       models.CharField(blank=True, max_length=25, choices=[('biopsie','Biopsie'),('exerese_chirurgicale','Exérèse chirurgicale'),('cytoponction','Cytoponction'),('liquide_biologique','Liquide biologique'),('autopsie','Autopsie')])),
        migrations.AddField('Diagnostic', 'qualite_prelevement',         models.CharField(blank=True, max_length=15, choices=[('adequate','Adéquate'),('limite','Limitée'),('inadequat','Inadéquate')])),
        migrations.AddField('Diagnostic', 'immunohistochimie',           models.TextField(blank=True)),
        migrations.AddField('Diagnostic', 'rapport_complet',             models.TextField(blank=True)),
        migrations.AddField('Diagnostic', 'marges_chirurgicales',        models.CharField(blank=True, max_length=20, choices=[('r0','Saines (R0)'),('r1','Microscopiques (R1)'),('r2','Macroscopiques (R2)'),('non_evaluables','Non évaluables')])),
        migrations.AddField('Diagnostic', 'distance_marge_minimale',     models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField('Diagnostic', 'emboles_lymphatiques',        models.BooleanField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'emboles_vasculaires',         models.BooleanField(blank=True, null=True)),
        migrations.AddField('Diagnostic', 'modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics_modifies', to=settings.AUTH_USER_MODEL)),
        # Modifier taille_tumeur max_digits
        migrations.AlterField('Diagnostic', 'taille_tumeur', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, help_text='mm')),

        # Nouveau modèle StyleVie
        migrations.CreateModel(
            name='StyleVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_vie', to='diagnostics.diagnostic')),
                ('statut_tabagique',        models.CharField(blank=True, max_length=20, choices=[('non_fumeur','Non-fumeur'),('fumeur_actif','Fumeur actif'),('ancien_fumeur','Ancien fumeur'),('fumeur_passif','Fumeur passif'),('inconnu','Inconnu')])),
                ('paquets_annees',          models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('age_debut_tabac',         models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_arret_tabac',         models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type_tabac',              models.CharField(blank=True, max_length=100)),
                ('nombre_cigarettes_jour',  models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consommation_alcool',     models.CharField(blank=True, max_length=20, choices=[('jamais','Jamais'),('occasionnel','Occasionnel'),('modere','Modéré'),('eleve','Élevé'),('ancien_buveur','Ancien buveur'),('inconnu','Inconnu')])),
                ('unites_par_semaine',      models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('type_alcool',             models.CharField(blank=True, max_length=100)),
                ('duree_consommation_annees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('niveau_activite',         models.CharField(blank=True, max_length=15, choices=[('sedentaire','Sédentaire'),('leger','Léger'),('modere','Modéré'),('intense','Intense'),('inconnu','Inconnu')])),
                ('heures_par_semaine',      models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('type_activite',           models.CharField(blank=True, max_length=200)),
                ('frequence_activite',      models.CharField(blank=True, max_length=50)),
                ('poids',                   models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille',                  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc',                     models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fruits_legumes_quotidien', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alimentation_desc',       models.TextField(blank=True)),
                ('regime_particulier',      models.CharField(blank=True, max_length=100)),
                ('exposition_professionnelle', models.TextField(blank=True)),
                ('duree_exposition_annees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profession',              models.CharField(blank=True, max_length=150)),
                ('stress_chronique',        models.BooleanField(blank=True, null=True)),
                ('qualite_sommeil',         models.CharField(blank=True, max_length=15, choices=[('bonne','Bonne'),('insuffisante','Insuffisante'),('excessive','Excessive'),('troubles','Troubles'),('inconnu','Inconnu')])),
                ('heures_sommeil',          models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('contraception_hormonale', models.CharField(blank=True, max_length=100)),
                ('allaitement_duree_mois',  models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_risque_global',     models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={'db_table': 'style_vie', 'verbose_name': 'Style de vie'},
        ),
    ]