# Generated by Django 6.0.2 on 2026-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_add_fields_stylévie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='est_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='ki67',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='metastases_sites',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='performance_status',
            field=models.CharField(blank=True, choices=[('0', 'PS 0 – Activité normale'), ('1', 'PS 1 – Symptômes, ambulatoire'), ('2', 'PS 2 – Alité <50% du temps'), ('3', 'PS 3 – Alité >50% du temps'), ('4', 'PS 4 – Invalide, alité'), ('U', 'Inconnu')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='psa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='taille_tumeur',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='tnm_certitude',
            field=models.CharField(blank=True, choices=[('certain', 'Certain'), ('probable', 'Probable'), ('suppose', 'Supposé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stylevie',
            name='consommation_alcool',
            field=models.CharField(blank=True, choices=[('jamais', 'Jamais'), ('occasionnel', 'Occasionnel (<1/semaine)'), ('modere', 'Modéré (1-7/semaine)'), ('eleve', 'Élevé (>7/semaine)'), ('ancien_buveur', 'Ancien buveur'), ('inconnu', 'Inconnu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stylevie',
            name='niveau_activite',
            field=models.CharField(blank=True, choices=[('sedentaire', 'Sédentaire'), ('leger', 'Léger (<2h/sem)'), ('modere', 'Modéré (2-5h/sem)'), ('intense', 'Intense (>5h/sem)'), ('inconnu', 'Inconnu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stylevie',
            name='qualite_sommeil',
            field=models.CharField(blank=True, choices=[('bonne', 'Bonne (7-9h)'), ('insuffisante', 'Insuffisante (<6h)'), ('excessive', 'Excessive (>10h)'), ('troubles', 'Troubles du sommeil'), ('inconnu', 'Inconnu')], max_length=15),
        ),
    ]
