# Generated by Django 6.0.2 on 2026-03-04 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_add_targeted_therapy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='alk',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='apc',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='autres_alterations',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='braf',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='braf_variant',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='brca1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='brca2',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='cdh1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='date_test_moleculaire',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='egfr',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='egfr_exon',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='kras',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='kras_codon',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='laboratoire_moleculaire',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='met',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='met_exon14',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='msi_statut',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='nf1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='nras',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='panel_ngs',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='pik3ca',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='rb1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='resistances_connues',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='ret',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='ros1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='therapie_ciblee_recommandee',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='tmb',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='tmb_statut',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='tp53',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='vhl',
        ),
        migrations.CreateModel(
            name='DiagnosticFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='diagnostics/files/')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('taille', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='diagnostics.diagnostic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
