# Generated by Django 4.2.9 on 2026-03-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_remove_diagnostic_alk_remove_diagnostic_apc_and_more'),
        ('diagnostics', '0006_diagnostic_afp_diagnostic_ca_125_diagnostic_ca_19_9_and_more'),
    ]

    operations = [
    ]
