# Generated by Django 5.2.8 on 2026-02-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnostics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSuivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_consultation",
                    models.CharField(
                        choices=[
                            ("suivi", "Suivi standard"),
                            ("post_trt", "Post-traitement"),
                            ("urgence", "Urgence"),
                            ("bilan", "Bilan d'extension"),
                            ("annonce", "Consultation d'annonce"),
                            ("palliative", "Soins palliatifs"),
                            ("psycho", "Psycho-oncologie"),
                            ("dietet", "Diététique"),
                        ],
                        default="suivi",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("realisee", "Réalisée"),
                            ("annulee", "Annulée"),
                            ("reportee", "Reportée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("date_consultation", models.DateField()),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                (
                    "poids_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("taille_cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ta_systolique",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Tension artérielle systolique mmHg",
                        null=True,
                    ),
                ),
                (
                    "ta_diastolique",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Tension artérielle diastolique mmHg",
                        null=True,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "frequence_cardiaque",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ps_ecog",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "PS 0 – Asymptomatique"),
                            (1, "PS 1 – Symptomatique, activité normale"),
                            (2, "PS 2 – Symptomatique, alité <50% de la journée"),
                            (3, "PS 3 – Alité >50% de la journée"),
                            (4, "PS 4 – Grabataire"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "evolution_maladie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stable", "Stable"),
                            ("regression", "Régression"),
                            ("progression", "Progression"),
                            ("remission", "Rémission complète"),
                            ("inconnu", "Non évaluable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "marqueurs_biologiques",
                    models.TextField(blank=True, help_text="CEA, CA125, PSA, etc."),
                ),
                ("motif", models.TextField(blank=True)),
                ("examen_clinique", models.TextField(blank=True)),
                ("conclusion", models.TextField(blank=True)),
                (
                    "conduite_a_tenir",
                    models.TextField(
                        blank=True,
                        help_text="CAT : examens, traitements, prochaine consultation",
                    ),
                ),
                ("prochaine_consultation", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_realisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation de suivi",
                "db_table": "consultations_suivi",
                "ordering": ["-date_consultation"],
            },
        ),
        migrations.CreateModel(
            name="EvenementClinique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("hospit", "Hospitalisation"),
                            ("complic", "Complication"),
                            ("recidive", "Récidive / Rechute"),
                            ("meta", "Nouvelle métastase"),
                            ("toxicite", "Toxicité traitement"),
                            ("deces", "Décès"),
                            ("remission", "Remission confirmée"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Grade 1 – Légère"),
                            ("2", "Grade 2 – Modérée"),
                            ("3", "Grade 3 – Sévère"),
                            ("4", "Grade 4 – Critique"),
                            ("5", "Grade 5 – Décès"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_evenement", models.DateField()),
                ("date_resolution", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "traitement_consequence",
                    models.TextField(
                        blank=True, help_text="Impact sur le traitement en cours"
                    ),
                ),
                (
                    "hospitalisation_duree",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Durée en jours", null=True
                    ),
                ),
                (
                    "lien_traitement",
                    models.CharField(
                        blank=True, help_text="Traitement en cause", max_length=200
                    ),
                ),
                ("resolu", models.BooleanField(default=False)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement clinique",
                "db_table": "evenements_cliniques",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.CreateModel(
            name="QualiteVie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "difficulte_activites_intenses",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "difficulte_longue_marche",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "difficulte_courte_marche",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "alite_journee",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "besoin_aide_repas_toilette",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_fatigue",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_nausees",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_douleur",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_dyspnee",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_insomnie",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_appetit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_constipation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_diarrhee",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_anxiete",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_depression",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "difficulte_sociale",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        null=True,
                    ),
                ),
                (
                    "score_global_sante",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Score global santé / QdV de 1 (très mauvais) à 7 (excellent)",
                        null=True,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qualite_vie",
                        to="suivi.consultationsuivi",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualites_vie",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation qualité de vie",
                "db_table": "qualites_vie",
                "ordering": ["-date_evaluation"],
            },
        ),
    ]
