# Generated by Django 5.2.8 on 2026-02-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "id_national",
                    models.CharField(
                        blank=True,
                        help_text="Numéro national d'identité",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("nom_jeune_fille", models.CharField(blank=True, max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("U", "Inconnu")],
                        max_length=1,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "age_diagnostic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("lieu_naissance", models.CharField(blank=True, max_length=100)),
                ("nationalite", models.CharField(default="Algérienne", max_length=50)),
                ("adresse", models.TextField(blank=True)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("wilaya", models.CharField(blank=True, max_length=100)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("telephone2", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "niveau_instruction",
                    models.CharField(
                        choices=[
                            ("0", "Aucun"),
                            ("1", "Primaire"),
                            ("2", "Moyen"),
                            ("3", "Secondaire"),
                            ("4", "Supérieur"),
                            ("9", "Inconnu"),
                        ],
                        default="9",
                        max_length=1,
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("AGR", "Agriculteur"),
                            ("FON", "Fonctionnaire"),
                            ("COM", "Commerçant"),
                            ("ART", "Artisan"),
                            ("ETU", "Étudiant"),
                            ("RET", "Retraité"),
                            ("SEM", "Sans emploi"),
                            ("FFO", "Femme au foyer"),
                            ("PSA", "Professionnel de santé"),
                            ("AUT", "Autre"),
                            ("INC", "Inconnu"),
                        ],
                        default="INC",
                        max_length=3,
                    ),
                ),
                (
                    "situation_familiale",
                    models.CharField(
                        choices=[
                            ("celibataire", "Célibataire"),
                            ("marie", "Marié(e)"),
                            ("divorce", "Divorcé(e)"),
                            ("veuf", "Veuf/Veuve"),
                            ("inconnu", "Inconnu"),
                        ],
                        default="inconnu",
                        max_length=20,
                    ),
                ),
                (
                    "nombre_enfants",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("antecedents_personnels", models.TextField(blank=True)),
                ("antecedents_familiaux", models.TextField(blank=True)),
                (
                    "tabagisme",
                    models.CharField(
                        choices=[
                            ("non", "Non-fumeur"),
                            ("ex", "Ex-fumeur"),
                            ("actif", "Fumeur actif"),
                            ("inconnu", "Inconnu"),
                        ],
                        default="inconnu",
                        max_length=20,
                    ),
                ),
                (
                    "alcool",
                    models.CharField(
                        choices=[
                            ("non", "Non"),
                            ("oui", "Oui"),
                            ("inconnu", "Inconnu"),
                        ],
                        default="inconnu",
                        max_length=20,
                    ),
                ),
                (
                    "statut_dossier",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("traitement", "En traitement"),
                            ("remission", "Rémission"),
                            ("perdu", "Perdu de vue"),
                            ("decede", "Décédé"),
                            ("archive", "Archivé"),
                        ],
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                (
                    "statut_vital",
                    models.CharField(
                        choices=[
                            ("vivant", "Vivant"),
                            ("decede", "Décédé"),
                            ("inconnu", "Inconnu"),
                            ("perdu", "Perdu de vue"),
                        ],
                        default="inconnu",
                        max_length=10,
                    ),
                ),
                ("date_deces", models.DateField(blank=True, null=True)),
                ("cause_deces", models.CharField(blank=True, max_length=200)),
                ("etablissement_pec", models.CharField(blank=True, max_length=200)),
                ("date_enregistrement", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medecin_referent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_suivis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["-date_enregistrement"],
            },
        ),
        migrations.CreateModel(
            name="ContactUrgence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("lien", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=20)),
                ("telephone2", models.CharField(blank=True, max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_urgence",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "contacts_urgence",
            },
        ),
    ]
