# Generated by Django 5.2.8 on 2026-02-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnostics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chimiotherapie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "intention",
                    models.CharField(
                        choices=[
                            ("curatif", "Curatif"),
                            ("palliatif", "Palliatif"),
                            ("adjuvant", "Adjuvant"),
                            ("neo_adjuvant", "Néo-adjuvant"),
                            ("prophylactique", "Prophylactique"),
                        ],
                        default="curatif",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("medecin", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "protocole",
                    models.CharField(
                        blank=True,
                        help_text="Ex: AC-T, FOLFOX, BEP, R-CHOP",
                        max_length=100,
                    ),
                ),
                (
                    "ligne",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Ligne de traitement (1ère, 2ème...)"
                    ),
                ),
                (
                    "nombre_cycles",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cycles_realises", models.PositiveSmallIntegerField(default=0)),
                (
                    "intervalle_jours",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Jours entre cycles", null=True
                    ),
                ),
                (
                    "voie_administration",
                    models.CharField(
                        choices=[
                            ("iv_perf", "IV Perfusion"),
                            ("iv_bolus", "IV Bolus"),
                            ("po", "Per os (oral)"),
                            ("sc", "Sous-cutanée"),
                            ("im", "Intramusculaire"),
                            ("it", "Intrathécale"),
                            ("autre", "Autre"),
                        ],
                        default="iv_perf",
                        max_length=20,
                    ),
                ),
                (
                    "reponse_tumorale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RC", "RC – Réponse Complète"),
                            ("RP", "RP – Réponse Partielle"),
                            ("SD", "SD – Stabilisation"),
                            ("PD", "PD – Progression"),
                            ("NE", "NE – Non Évaluable"),
                            ("NA", "Non Applicable"),
                        ],
                        max_length=5,
                    ),
                ),
                ("date_evaluation", models.DateField(blank=True, null=True)),
                (
                    "toxicite_grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1 – Légère"),
                            (2, "2 – Modérée"),
                            (3, "3 – Sévère"),
                            (4, "4 – Engageant le pronostic vital"),
                            (5, "5 – Décès"),
                        ],
                        null=True,
                    ),
                ),
                ("toxicite_description", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chimiothérapie",
                "verbose_name_plural": "Chimiothérapies",
                "db_table": "chimiotherapies",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Chirurgie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "intention",
                    models.CharField(
                        choices=[
                            ("curatif", "Curatif"),
                            ("palliatif", "Palliatif"),
                            ("adjuvant", "Adjuvant"),
                            ("neo_adjuvant", "Néo-adjuvant"),
                            ("prophylactique", "Prophylactique"),
                        ],
                        default="curatif",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("medecin", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "type_chirurgie",
                    models.CharField(
                        choices=[
                            ("curative", "Chirurgie curative"),
                            ("palliative", "Chirurgie palliative"),
                            ("cyto", "Chirurgie cytoréductrice"),
                            ("recons", "Chirurgie reconstructrice"),
                            ("diagnostic", "Chirurgie diagnostique / biopsie"),
                            ("ganglion", "Curage ganglionnaire"),
                            ("autre", "Autre"),
                        ],
                        default="curative",
                        max_length=20,
                    ),
                ),
                (
                    "intitule_acte",
                    models.CharField(
                        help_text="Ex: Mastectomie totale gauche + GS", max_length=300
                    ),
                ),
                (
                    "voie_abord",
                    models.CharField(
                        choices=[
                            ("ouverte", "Chirurgie ouverte"),
                            ("laparo", "Laparoscopie"),
                            ("thoraco", "Thoracoscopie"),
                            ("robot", "Chirurgie robotique"),
                            ("endo", "Endoscopie"),
                            ("autre", "Autre"),
                        ],
                        default="ouverte",
                        max_length=20,
                    ),
                ),
                ("chirurgien", models.CharField(blank=True, max_length=150)),
                (
                    "marges_resection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R0", "R0 – Résection complète (marges saines)"),
                            ("R1", "R1 – Résection microscopiquement incomplète"),
                            ("R2", "R2 – Résection macroscopiquement incomplète"),
                            ("RX", "RX – Non évaluable"),
                        ],
                        max_length=5,
                    ),
                ),
                ("curage_ganglionnaire", models.BooleanField(default=False)),
                (
                    "nb_ganglions_preleves",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "nb_ganglions_envahis",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("compte_rendu_operatoire", models.TextField(blank=True)),
                ("complications", models.TextField(blank=True)),
                (
                    "duree_hospitalisation",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Durée en jours", null=True
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chirurgie",
                "verbose_name_plural": "Chirurgies",
                "db_table": "chirurgies",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Hormonotherapie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "intention",
                    models.CharField(
                        choices=[
                            ("curatif", "Curatif"),
                            ("palliatif", "Palliatif"),
                            ("adjuvant", "Adjuvant"),
                            ("neo_adjuvant", "Néo-adjuvant"),
                            ("prophylactique", "Prophylactique"),
                        ],
                        default="curatif",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("medecin", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "type_hormonotherapie",
                    models.CharField(
                        choices=[
                            ("anti_estro", "Anti-estrogène (Tamoxifène)"),
                            ("anti_andro", "Anti-androgène"),
                            ("aromatase", "Inhibiteur de l'aromatase"),
                            ("lhrh", "Analogue LH-RH"),
                            ("progest", "Progestatif"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "molecule",
                    models.CharField(
                        help_text="DCI ex: Tamoxifène, Anastrozole", max_length=100
                    ),
                ),
                (
                    "dose_mg_jour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "duree_mois_prevue",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hormonothérapie",
                "verbose_name_plural": "Hormonothérapies",
                "db_table": "hormonotherapies",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Immunotherapie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "intention",
                    models.CharField(
                        choices=[
                            ("curatif", "Curatif"),
                            ("palliatif", "Palliatif"),
                            ("adjuvant", "Adjuvant"),
                            ("neo_adjuvant", "Néo-adjuvant"),
                            ("prophylactique", "Prophylactique"),
                        ],
                        default="curatif",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("medecin", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "type_immunotherapie",
                    models.CharField(
                        choices=[
                            ("checkpoint", "Inhibiteur de checkpoint"),
                            ("anti_her2", "Anti-HER2 (Trastuzumab...)"),
                            ("anti_vegf", "Anti-VEGF (Bevacizumab...)"),
                            ("anti_egfr", "Anti-EGFR (Cetuximab...)"),
                            ("imatinib", "Inhibiteur de tyrosine kinase"),
                            ("cart", "CAR-T Cell"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "molecule",
                    models.CharField(
                        help_text="DCI ex: Pembrolizumab, Trastuzumab", max_length=100
                    ),
                ),
                ("dose", models.CharField(blank=True, max_length=50)),
                (
                    "nombre_cycles",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "biomarqueur_cible",
                    models.CharField(
                        blank=True,
                        help_text="Ex: PDL1, HER2, EGFR, BRAF",
                        max_length=100,
                    ),
                ),
                (
                    "reponse_tumorale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RC", "RC"),
                            ("RP", "RP"),
                            ("SD", "SD"),
                            ("PD", "PD"),
                            ("NE", "NE"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immunothérapie / Thérapie ciblée",
                "verbose_name_plural": "Immunothérapies / Thérapies ciblées",
                "db_table": "immunotherapies",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="MedicamentChimio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dci",
                    models.CharField(
                        help_text="Dénomination Commune Internationale", max_length=100
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "unite_dose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mg/m2", "mg/m²"),
                            ("mg/kg", "mg/kg"),
                            ("mg", "mg"),
                            ("AUC", "AUC"),
                            ("UI", "UI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "jour_administration",
                    models.CharField(
                        blank=True, help_text="Ex: J1, J1-J5, J1,J8", max_length=50
                    ),
                ),
                (
                    "chimiotherapie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicaments",
                        to="treatments.chimiotherapie",
                    ),
                ),
            ],
            options={
                "db_table": "medicaments_chimio",
            },
        ),
        migrations.CreateModel(
            name="Radiotherapie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "intention",
                    models.CharField(
                        choices=[
                            ("curatif", "Curatif"),
                            ("palliatif", "Palliatif"),
                            ("adjuvant", "Adjuvant"),
                            ("neo_adjuvant", "Néo-adjuvant"),
                            ("prophylactique", "Prophylactique"),
                        ],
                        default="curatif",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("medecin", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("RTE", "Radiothérapie externe (RTE)"),
                            (
                                "RCMI",
                                "Radiothérapie conformationnelle avec modulation d'intensité (RCMI)",
                            ),
                            ("STRT", "Stéréotaxie (SBRT/SRST)"),
                            ("curie", "Curiethérapie"),
                            ("RTE_3D", "RTE conformationnelle 3D"),
                            ("tomo", "Tomothérapie"),
                            ("cyber", "CyberKnife"),
                            ("proton", "Protonthérapie"),
                            ("autre", "Autre"),
                        ],
                        default="RTE",
                        max_length=20,
                    ),
                ),
                ("site_irradie", models.CharField(max_length=200)),
                (
                    "dose_totale_gy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dose totale en Gray",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dose_par_seance_gy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dose par séance en Gray",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "nombre_seances",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("seances_realisees", models.PositiveSmallIntegerField(default=0)),
                (
                    "energie_mev",
                    models.CharField(
                        blank=True, help_text="Ex: 6MV, 15MV, 18MV", max_length=20
                    ),
                ),
                (
                    "association_chimio",
                    models.BooleanField(
                        default=False, help_text="Radiochimiothérapie concomitante"
                    ),
                ),
                ("toxicite_aigue", models.TextField(blank=True)),
                ("toxicite_tardive", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Radiothérapie",
                "verbose_name_plural": "Radiothérapies",
                "db_table": "radiotherapies",
                "ordering": ["-date_debut"],
            },
        ),
    ]
