# Generated by Django 6.0.2 on 2026-03-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_alter_diagnostic_est_principal_alter_diagnostic_ki67_and_more'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chimiotherapie',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chimiotherapie_set', to='diagnostics.diagnostic'),
        ),
        migrations.AlterField(
            model_name='chirurgie',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chirurgie_set', to='diagnostics.diagnostic'),
        ),
        migrations.AlterField(
            model_name='hormonotherapie',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hormonotherapie_set', to='diagnostics.diagnostic'),
        ),
        migrations.AlterField(
            model_name='immunotherapie',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunotherapie_set', to='diagnostics.diagnostic'),
        ),
        migrations.AlterField(
            model_name='radiotherapie',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiotherapie_set', to='diagnostics.diagnostic'),
        ),
    ]
